[rpc]
addr = ":9801"

[http]
addr = ":9800"
secret = "cxbwychbthy5ts33rab4bax5b65lyh30"

[db]
addr = "127.0.0.1:3306"
dsn = "root:123456@tcp(127.0.0.1:3306)/demo?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"

[log]
dir = "/tmp/larvalog/api/"